// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistencia;

namespace Persistencia.Migrations
{
    [DbContext(typeof(conexion))]
    [Migration("20210923200557_AgregarTablasBd")]
    partial class AgregarTablasBd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Dominio.Empleados", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("empleados");
                });

            modelBuilder.Entity("Dominio.Facturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("Dominio.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FacturasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacturasId");

                    b.ToTable("productos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Producto");
                });

            modelBuilder.Entity("Dominio.ConsolasP", b =>
                {
                    b.HasBaseType("Dominio.Producto");

                    b.HasDiscriminator().HasValue("ConsolasP");
                });

            modelBuilder.Entity("Dominio.Controles", b =>
                {
                    b.HasBaseType("Dominio.Producto");

                    b.HasDiscriminator().HasValue("Controles");
                });

            modelBuilder.Entity("Dominio.VideoJuego", b =>
                {
                    b.HasBaseType("Dominio.Producto");

                    b.HasDiscriminator().HasValue("VideoJuego");
                });

            modelBuilder.Entity("Dominio.Producto", b =>
                {
                    b.HasOne("Dominio.Facturas", null)
                        .WithMany("Producto")
                        .HasForeignKey("FacturasId");
                });

            modelBuilder.Entity("Dominio.Facturas", b =>
                {
                    b.Navigation("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
